version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.1
    - 1.21.1
    - 1.21.2
    - 1.21.3
  - dependency-name: "@graphql-codegen/typescript-react-apollo"
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: "@graphql-codegen/introspection"
    versions:
    - 1.18.1
